### ISSUE TITLE
Cpu usage

### ISSUE THREAD

**Issue by zigomatichub** [hassio-addons/addon-emqx#25] opened 2023-01-31 19:48 UTC
# Problem/Motivation

Cpu usage is taking 15% on pi4 with V0.2.1 for the addon-emqx

Is it expected ?

**Comment by frenck** [comment] 2023-01-31 23:32
I don't see that level of usage myself on my production system (Home Assistant Yellow, which is equivalent to a Pi4 in terms of CPU), using Zigbee2MQTT with around 70 devices. It is hovering around 1-2%, with some smaller spikes at times (probably caused by processing/taking up/pushing out data).

It is expected to be heavier than, for example, mosquito. If you are looking for using as less resources as possible mosquito would be a way better choice.

../Frenck

**Comment by mundschenk-at** [comment] 2023-02-01 19:45
I don't have Zigbee2MQTT, but I did notice a large baseline increase in CPU usage when I switched from Mosquitto to the EMQX add-on.
<img width="1338" alt="image" src="https://user-images.githubusercontent.com/6943905/216146727-8bed25dd-6cac-49e4-92a6-624e30db2805.png">

I've since tracked this to the `beam.smp` process which had an unresolved issue for previous versions that staled out. I am assuming this is something of a configuration issue, but it's kind of hard to pinpoint (and I'm running mostly the default configuration, EMQX is a bit overwhelming).

**Comment by mundschenk-at** [comment] 2023-02-02 21:53
So I don't really know if this connected at all, but the docker container always appears `unhealthy` because the health check `emqx_ctl status` fails with `ERROR: node_is_not_running!`. Apparently this is a [common issue with running EMQX in Docker](https://techoverflow.net/2022/09/27/how-to-fix-docker-emqx_ctl-node-emqxnode1-emqx-mydomain-com-not-responding-to-pings/), but strangely `homeassistant.local` is reachable from the command line, only the Erlang engine does not seem to be able to so.

As a test, I changed my node name to `emqx@127.0.0.1` using the environment variables and that allowed the health check to pass. It did not reduce the CPU usage (in fact it spiked, but that was probably because the node configuration did not port over completely, e.g. the authorized user list appeared to be empty and clients could not connect).

**Comment by mkh595** [comment] 2023-02-04 08:41
I observe same issue on RPI4. CPU usage increased from 5% to 20%. And it is just only running. No devices connected yet, no mqtt messages sent yet.

![image](https://user-images.githubusercontent.com/30566575/216757711-beb7f298-c79d-4a6c-ac64-2f9ec0365c01.png)

**Comment by Woutch** [comment] 2023-02-07 08:21
Same over here, 
Disabled mosquitto and installed, EMQX, added local user DB. Created 4 users. Everything worked perfect. But Home assistant total CPU usage jumped from 2% to 20% on 2 cores of my I5-11400. 

Switching back to Mosquitto and CPU was back at 1-2%.

If I can check something specific, let me know.

Running Home assistant in Qemu (Unraid).

Best regards,
Wouter

**Comment by wax911** [comment] 2023-02-26 16:27
Same here, this is my cpu usage after migrating to EMQX
![image](https://user-images.githubusercontent.com/7859175/221423053-8b414559-a360-4c7a-b55e-aabb08fc2b80.png)

**Comment by 8OND007** [comment] 2023-03-12 12:47
Same here. 

I testdrived EMQX MQTT broker instead of standaard Mosquito MQTT broker for some weeks. (from 28/03/2023)
I noticed a CPU increase from 22% to 65% ! 
In between it dropped from 65% to still 50% (think it was with EMQX addon update around 8/3/2023.

Because I was device rebooting (trying to get rid of broker Music Assistant v1) I noticed very long waiting times and high CPU load, It took some time to pinpoint that to the EMQX MQTT broker.

I liked the EMQX broker with it's full options to debug/dashboards/... but not at cost of 25% to 40% CPU increase and a slower HA.
Below my CPU load grafana trend : 

![EMQX broker higher CPU load than Mosquito MQTT broker](https://user-images.githubusercontent.com/43314247/224545550-f0e9a6db-3e3c-43a8-8369-69a166abdff4.png)

FYI, I'm running latest HA (OS) virtually on a ESXi on an industrial NUC.

**Comment by mundschenk-at** [comment] 2023-04-13 17:00
Still an issue.

**Comment by mundschenk-at** [comment] 2023-04-18 16:56
With the upgrade to HAOS 10, CPU usage has risen a further 5 percentage points on average
<img width="1357" alt="image" src="https://user-images.githubusercontent.com/6943905/232849445-ee4693b7-be6e-4b0d-b6b9-2b204cbccba7.png">

**Comment by frenck** [comment] 2023-04-18 17:56
🤷 From an add-on perspective, there is not much to do. EMQX is heavier. If that doesn't fit your, please use Mosquitto.

**Comment by mundschenk-at** [comment] 2023-04-18 17:59
Sure. But the fact that it change so much with HAOS (and thus likely related to the Docker version/kernel limit changes) makes me pretty certain it is tunable.

**Comment by frenck** [comment] 2023-04-18 18:00
Feel free to do so, but I'm not considering it an issue.

**Comment by mundschenk-at** [comment] 2023-04-18 18:03
That's of course your prerogative, but the default settings might not be a good fit for an add-on and could be improved for this use case.

**Comment by frenck** [comment] 2023-04-18 18:08
> your prerogative

Yup. My add-on.

>  could be improved for this use case.

You mean your use-case.

That said, enhancements/improvement PRs are always welcome.

Anyways, as said above, this is not a problem I will address or consider an issue.
Therefore, closing this issue.

../Frenck

**Closed by frenck** 2023-04-18 18:08 UTC

**Comment by mundschenk-at** [comment] 2023-04-18 18:11
With use-case I meant "HA add-on" as opposed to "generic Docker image". If I find out anything useful, I'll make a PR.
