### ISSUE TITLE
EMQX won't start

### ISSUE THREAD

**Issue by Dutchy-79** [hassio-addons/addon-emqx#15] opened 2022-11-26 12:45 UTC
# Problem/Motivation

Wanted to change from mosquitto to emqx because my mqqt connected devices keep getting unavailable several times per hour. 

> (Why the issue was filed)

Installed EMQX from HA addon repo, Stopped mosquitto, start EMXQ, Failled to start.
Rebooted HA with mosquitto start on boot turned off (to be sure stop might not be a full stop) then started EMQX and same error.

## Expected behavior

> (What you expected to happen)

Start EMQX

## Actual behavior

> (What actually happened)

EMQX not starting

## Steps to reproduce

> (How can someone else make/see it happen)

IDK, I think it should work fine though for me it does not start at all.

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

EMQX
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/00-banner.sh
-----------------------------------------------------------
 Add-on: EMQX
 The most scalable open-source MQTT broker for IoT. An alternative for the Mosquitto add-on
-----------------------------------------------------------
 Add-on version: 0.1.3
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.3  (amd64 / qemux86-64)
 Home Assistant Core: 2022.11.4
 Home Assistant Supervisor: 2022.11.2
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/01-log-level.sh
cont-init: info: /etc/cont-init.d/01-log-level.sh exited 0
cont-init: info: running /etc/cont-init.d/02-set-timezone.sh
[13:36:19] INFO: Configuring timezone
cont-init: info: /etc/cont-init.d/02-set-timezone.sh exited 0
cont-init: info: running /etc/cont-init.d/emqx.sh
cont-init: info: /etc/cont-init.d/emqx.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun emqx (no readiness notification)
s6-rc: info: service legacy-services successfully started
[13:36:19] INFO: Starting EMQX...
plugins.install_dir = EMQX_PLUGINS__INSTALL_DIR = "/data/emqx/plugins"
rpc.port_discovery = EMQX_RPC__PORT_DISCOVERY = manual
log.file_handlers.default.enable = EMQX_LOG__FILE_HANDLERS__DEFAULT__ENABLE = false
log.console_handler.enable = EMQX_LOG__CONSOLE_HANDLER__ENABLE = true
node.data_dir = EMQX_NODE__DATA_DIR = "/data/emqx/data"
node.cookie = EMQX_NODE__COOKIE = ******
node.name = EMQX_NODE__NAME = emqx@homeassistant.local
Listener ssl:default on 0.0.0.0:8883 started.
Listener tcp:default on 0.0.0.0:1883 started.
2022-11-26T13:36:32.784352+01:00 [error] Failed to start Ranch listener 'ws:default' in ranch_tcp:listen([{cacerts,'...'},{key,'...'},{cert,'...'},{ip,{0,0,0,0}},{port,8083},{backlog,1024},{buffer,4096},{high_watermark,1048576},{nodelay,true},{send_timeout,15000},{send_timeout_close,true}]) for reason eaddrinuse (address already in use)
2022-11-26T13:36:32.784622+01:00 [error] Supervisor: {<0.2171.0>,ranch_listener_sup}. Context: start_error. Reason: {listen_error,'ws:default',eaddrinuse}. Offender: id=ranch_acceptors_sup,pid=undefined.
Failed to start listener ws:default on 0.0.0.0:8083: eaddrinuse.
2022-11-26T13:36:32.784805+01:00 [error] crasher: initial call: supervisor:ranch_acceptors_sup/1, pid: <0.2173.0>, registered_name: [], exit: {{listen_error,'ws:default',eaddrinuse},[{ranch_acceptors_sup,listen_error,5,[{file,"ranch_acceptors_sup.erl"},{line,66}]},{supervisor,init,1,[{file,"supervisor.erl"},{line,330}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,423}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,390}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}, ancestors: [<0.2171.0>,ranch_sup,<0.1909.0>], message_queue_len: 0, messages: [], links: [<0.2171.0>], dictionary: [{logger,error_logger}], trap_exit: true, status: running, heap_size: 2586, stack_size: 29, reductions: 9194; neighbours:
2022-11-26T13:36:32.785760+01:00 [error] crasher: initial call: application_master:init/4, pid: <0.2031.0>, registered_name: [], exit: {{bad_return,{{emqx_app,start,[normal,[]]},{'EXIT',{{failed_to_start,"ws:default(0.0.0.0:8083) : eaddrinuse"},[{emqx_listeners,'-foreach_listeners/1-fun-0-',2,[{file,"emqx_listeners.erl"},{line,625}]},{lists,foreach,2,[{file,"lists.erl"},{line,1342}]},{emqx_app,maybe_start_listeners,0,[{file,"emqx_app.erl"},{line,90}]},{emqx_app,start,2,[{file,"emqx_app.erl"},{line,50}]},{application_master,start_it_old,4,[{file,"application_master.erl"},{line,293}]}]}}}},[{application_master,init,4,[{file,"application_master.erl"},{line,142}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}, ancestors: [<0.2030.0>], message_queue_len: 1, messages: [{'EXIT',<0.2032.0>,normal}], links: [<0.2030.0>,<0.1688.0>], dictionary: [], trap_exit: true, status: running, heap_size: 987, stack_size: 29, reductions: 160; neighbours:
[os_mon] memory supervisor port (memsup): Erlang has closed
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed
{"Kernel pid terminated",application_controller,"{application_start_failure,emqx,{bad_return,{{emqx_app,start,[normal,[]]},{'EXIT',{{failed_to_start,\"ws:default(0.0.0.0:8083) : eaddrinuse\"},[{emqx_listeners,'-foreach_listeners/1-fun-0-',2,[{file,\"emqx_listeners.erl\"},{line,625}]},{lists,foreach,2,[{file,\"lists.erl\"},{line,1342}]},{emqx_app,maybe_start_listeners,0,[{file,\"emqx_app.erl\"},{line,90}]},{emqx_app,start,2,[{file,\"emqx_app.erl\"},{line,50}]},{application_master,start_it_old,4,[{file,\"application_master.erl\"},{line,293}]}]}}}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,emqx,{bad_return,{{emqx_app,start,[normal,[]]},{'EXIT',{{failed_to_start,"ws:default(0.0.0.0:8083) : eaddrinuse"},[{emqx_listeners,'-foreach_listeners/1-fun-0-',2,[{file,"emqx_listeners.erl"},{line,625}]},{lists,foreach,2,[{file,"lists.erl"},{line,1342}]},{emqx_app,maybe_start_listeners,0,[{file,"emqx_app.erl"},{line,90}]},{emqx_app,start,2,[{file,"emqx_app.erl"},{line,50}]},{application_master,start_it_old,4,[{file,"application_master.erl"},{line,293}]}]}}}}})

Crash dump is being written to: log/erl_crash.dump...done
[13:36:42] WARNING: EMQX crashed, halting add-on
s6-rc: info: service legacy-services: stopping
[13:36:42] INFO: EMQX stopped, restarting...
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by frenck** [comment] 2022-11-28 08:12
```
2022-11-26T13:36:32.784352+01:00 [error] Failed to start Ranch listener 'ws:default' in ranch_tcp:listen([{cacerts,'...'},{key,'...'},{cert,'...'},{ip,{0,0,0,0}},{port,8083},{backlog,1024},{buffer,4096},{high_watermark,1048576},{nodelay,true},{send_timeout,15000},{send_timeout_close,true}]) for reason eaddrinuse (address already in use)
```

Port 8083 is already in use on your system, which EMQX tries to allocate as well.
Either free that port up, or temporarily shut down the process currently occupying that port, so you can start up EMQX to change it.

Closing this issue, as it is not a bug.

../Frenck

**Closed by frenck** 2022-11-28 08:12 UTC
